%YAML:1.0

#--------------------------------------------------------------------------------------------
# 生成球体的参数
#--------------------------------------------------------------------------------------------
# 当我们生成球之后,保存的文件名
sphere.filename: sphere_hasnoise.g2o
# 球上每圈有多少个节点
sphere.nodesPerLevel: 50
# 机器人在球体周围移动的次数
sphere.laps: 50
# 该球的半径
sphere.radius: 100
# 设置平移的噪声级别
noiseTranslation.x: 0.01
noiseTranslation.y: 0.01
noiseTranslation.z: 0.01
# 设置旋转的噪声
noiseRotation.x: 0.005
noiseRotation.y: 0.005
noiseRotation.z: 0.005
# 1表示true,0表示false
# 是否使用随机种子生成球
sphere.randomSeed: 0
#--------------------------------------------------------------------------------------------
# 优化后的位置
#--------------------------------------------------------------------------------------------
sphere.optimizeFilename: sphere_optimize.g2o